import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const ORANGE = [230, 100, 50] as const;
const MUTED_TEXT = [160, 160, 170] as const;

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_TEXT);
    doc.text(
      `Generated by Elite Performance App — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
}

export interface AthleteReportData {
  name: string;
  sport: string;
  weight: number | null;
  wellnessAvg: { sleep: number; soreness: number; fatigue: number; overall: number } | null;
  topRecords: { name: string; value: number; unit: string; date: string }[];
  chartImageBase64: string | null;
  chartTitle: string;
}

export function exportAthleteReport(data: AthleteReportData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 15;

  // ─── Header ───
  doc.setFillColor(...ORANGE);
  doc.rect(0, 0, pageW, 32, "F");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(data.name, 14, 18);
  doc.setFontSize(11);
  doc.text(`${data.sport.toUpperCase()}${data.weight ? `  •  ${data.weight} kg` : ""}`, 14, 26);
  y = 40;

  // ─── Wellness Summary ───
  doc.setFontSize(14);
  doc.setTextColor(...ORANGE);
  doc.text("Wellness Summary (Last 7 Days)", 14, y);
  y += 3;

  if (data.wellnessAvg) {
    autoTable(doc, {
      startY: y,
      head: [["Metric", "Average (1-6)"]],
      body: [
        ["Sleep", data.wellnessAvg.sleep.toFixed(1)],
        ["Soreness", data.wellnessAvg.soreness.toFixed(1)],
        ["Fatigue", data.wellnessAvg.fatigue.toFixed(1)],
        ["Overall", data.wellnessAvg.overall.toFixed(1)],
      ],
      theme: "grid",
      headStyles: { fillColor: [...ORANGE], textColor: [255, 255, 255], fontStyle: "bold" },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(10);
    doc.setTextColor(...MUTED_TEXT);
    doc.text("No wellness data in the last 7 days.", 14, y + 6);
    y += 14;
  }

  // ─── Top 5 Records ───
  doc.setFontSize(14);
  doc.setTextColor(...ORANGE);
  doc.text("Top 5 Records", 14, y);
  y += 3;

  if (data.topRecords.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [["Test", "Result", "Date"]],
      body: data.topRecords.map(r => [r.name, `${r.value} ${r.unit}`, r.date]),
      theme: "grid",
      headStyles: { fillColor: [...ORANGE], textColor: [255, 255, 255], fontStyle: "bold" },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(10);
    doc.setTextColor(...MUTED_TEXT);
    doc.text("No records available.", 14, y + 6);
    y += 14;
  }

  // ─── Chart ───
  if (data.chartImageBase64) {
    doc.setFontSize(14);
    doc.setTextColor(...ORANGE);
    doc.text(`Performance: ${data.chartTitle}`, 14, y);
    y += 4;
    const chartW = pageW - 28;
    const chartH = chartW * 0.45;
    if (y + chartH > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 15;
    }
    doc.addImage(data.chartImageBase64, "PNG", 14, y, chartW, chartH);
    y += chartH + 10;
  }

  // ─── Coach's Note ───
  if (y > doc.internal.pageSize.getHeight() - 60) {
    doc.addPage();
    y = 15;
  }
  doc.setFontSize(14);
  doc.setTextColor(...ORANGE);
  doc.text("Coach's Notes", 14, y);
  y += 5;
  doc.setDrawColor(...MUTED_TEXT);
  doc.setLineWidth(0.3);
  for (let i = 0; i < 5; i++) {
    doc.line(14, y + i * 8, pageW - 14, y + i * 8);
  }

  addFooter(doc);
  doc.save(`${data.name.replace(/\s+/g, "_")}_Performance_Report.pdf`);
}

export interface TeamSessionReportData {
  teamName: string;
  testName: string;
  testUnit: string;
  sessionDate: string;
  athletes: { name: string; value: number | null; present: boolean }[];
}

export function exportTeamSessionReport(data: TeamSessionReportData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 15;

  // ─── Header ───
  doc.setFillColor(...ORANGE);
  doc.rect(0, 0, pageW, 32, "F");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(`${data.teamName} — Session Report`, 14, 18);
  doc.setFontSize(11);
  doc.text(`${data.testName}  •  ${data.sessionDate}`, 14, 26);
  y = 40;

  // ─── Stats ───
  const presentValues = data.athletes.filter(a => a.present && a.value !== null).map(a => a.value!);
  const avg = presentValues.length ? (presentValues.reduce((a, b) => a + b, 0) / presentValues.length) : null;
  const best = presentValues.length ? Math.max(...presentValues) : null;
  const worst = presentValues.length ? Math.min(...presentValues) : null;
  const absentCount = data.athletes.filter(a => !a.present || a.value === null).length;

  doc.setFontSize(14);
  doc.setTextColor(...ORANGE);
  doc.text("Session Statistics", 14, y);
  y += 3;

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Athletes Tested", `${presentValues.length} / ${data.athletes.length}`],
      ["Average", avg !== null ? `${avg.toFixed(1)} ${data.testUnit}` : "—"],
      ["Best Performance", best !== null ? `${best} ${data.testUnit}` : "—"],
      ["Lowest Performance", worst !== null ? `${worst} ${data.testUnit}` : "—"],
      ["Absent", String(absentCount)],
    ],
    theme: "grid",
    headStyles: { fillColor: [...ORANGE], textColor: [255, 255, 255], fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 3 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // ─── Full Roster ───
  doc.setFontSize(14);
  doc.setTextColor(...ORANGE);
  doc.text("Full Roster", 14, y);
  y += 3;

  const sortedAthletes = [...data.athletes].sort((a, b) => {
    if (a.value === null && b.value === null) return 0;
    if (a.value === null) return 1;
    if (b.value === null) return -1;
    return b.value - a.value;
  });

  autoTable(doc, {
    startY: y,
    head: [["#", "Athlete", `Result (${data.testUnit})`, "Status"]],
    body: sortedAthletes.map((a, i) => [
      String(i + 1),
      a.name,
      a.present && a.value !== null ? String(a.value) : "—",
      a.present && a.value !== null ? "✓" : "Absent",
    ]),
    theme: "grid",
    headStyles: { fillColor: [...ORANGE], textColor: [255, 255, 255], fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 3 },
    margin: { left: 14, right: 14 },
  });

  addFooter(doc);
  doc.save(`${data.teamName.replace(/\s+/g, "_")}_Session_${data.sessionDate}.pdf`);
}
